In [233]:
import sqlite3
import pandas as pd
con=sqlite3.connect(r'C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\data\raw\ipl.db')


def q(sql):
     return pd.read_sql(sql, con)

In [234]:
def run_sql_file(path):
    with open(path,'r') as f:
        script=f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [235]:
q("""
-- what is the strike rate of every batter in the death overs

SELECT batter,
ROUND(
    100.0 * SUM(batter_runs) / SUM(
        CASE
            WHEN is_wide_ball = 0 AND is_no_ball = 0 THEN 1
            ELSE 0
        END
    ),
    2
) AS strike_rate

FROM deliveries
WHERE over_number >= 15 AND is_super_over = 0
GROUP BY batter;""")

             batter  strike_rate
0    A Ashish Reddy       146.58
1          A Badoni       165.03
2        A Chandila        57.14
3          A Chopra        50.00
4       A Choudhary       125.00
..              ...          ...
637      Yash Dayal        50.00
638   Yashpal Singh       130.77
639   Yudhvir Singh       166.67
640    Yuvraj Singh       183.40
641          Z Khan       100.00

[642 rows x 2 columns]

In [236]:
run_sql_file(r"C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\09_analysis_viewes.sql")

ran C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\09_analysis_viewes.sql

In [237]:
q("""SELECT *
 FROM v_ball;
""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [238]:
q(""" SELECT phase, count(*) FROM v_ball GROUP BY phase;""")

       phase  count(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [239]:
run_sql_file(r'C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\09_analysis_viewes.sql')

ran C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\09_analysis_viewes.sql

In [240]:
q("""SELECT * FROM v_innings;""")

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
...,...,...,...,...,...,...,...
2413,1529284,2,Sunrisers Hyderabad,Mumbai Indians,249,4,112
2414,1529285,1,Royal Challengers Bangalore,Gujarat Titans,155,10,116
2415,1529285,2,Gujarat Titans,Royal Challengers Bangalore,158,6,95
2416,1529286,1,Rajasthan Royals,Delhi Capitals,225,6,120
2417,1529286,2,Delhi Capitals,Rajasthan Royals,226,3,115

In [241]:
run_sql_file(r'C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\09_analysis_viewes.sql')

ran C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\09_analysis_viewes.sql

In [242]:
q("""
SELECT * FROM v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,225,Rajasthan Royals,1

In [243]:
q("""
SELECT * FROM v_ball;""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [244]:
q("""SELECT count(*) FROM v_match_totals;""")

   count(*)
0      1187

In [245]:
q("""SELECT COUNt(*) FROM v_innings ;""")

   COUNt(*)
0      2418

In [246]:
q("""SELECT phase,COUNT(*)FROM v_ball;""")

       phase  COUNT(*)
0  Powerplay    288051

In [247]:
q("""
-- Give the list of highest runs scored in IPL history
--Max 5
SELECT batter,
       SUM(batter_runs) AS total_runs
FROM v_ball
GROUP BY batter
ORDER BY total_runs DESC
LIMIT 5;
""")

      batter  total_runs
0    V Kohli        9040
1  RG Sharma        7183
2   S Dhawan        6769
3  DA Warner        6565
4   KL Rahul        5655

In [248]:
q("""
-- Give the list of highest sixes scored in IPL history
--Max 10
SELECT batter,
       COUNT(*) AS total_sixes
FROM v_ball
WHERE batter_runs = 6
GROUP BY batter
ORDER BY total_sixes DESC
LIMIT 10;
""")

           batter  total_sixes
0        CH Gayle          357
1       RG Sharma          311
2         V Kohli          307
3        MS Dhoni          264
4  AB de Villiers          251
5       DA Warner          236
6       SV Samson          234
7        KL Rahul          232
8      AD Russell          223
9      KA Pollard          223

In [249]:
q("""
--highest ball faced by a player,total runs,strike rate
--strike rate = (total runs/total balls)*100
select batter,
       sum(is_legal) as balls,
         sum(batter_runs) as runs,
            round(100.0 * sum(batter_runs) / sum(is_legal), 2) as strike_rate
            from v_ball
            group by batter
            order by balls desc
            limit 10;
            """)

       batter  balls  runs  strike_rate
0     V Kohli   6730  9040       134.32
1   RG Sharma   5396  7183       133.12
2    S Dhawan   5302  6769       127.67
3   DA Warner   4675  6565       140.43
4   AM Rahane   4141  5194       125.43
5    KL Rahul   4059  5655       139.32
6    SK Raina   4022  5528       137.44
7    MS Dhoni   3935  5439       138.22
8  RV Uthappa   3782  4952       130.94
9  KD Karthik   3567  4842       135.74

In [250]:
q("""
--batter who scored the highest share of runs in boundary

select batter,
         sum(batter_runs) as runs,
         round(100.0 *sum(case when batter_runs in (4,6) 
         then batter_runs
         else 0
         end)/sum(batter_runs),2)as boundary_perc

from v_ball
group by batter
having runs>2000
order by boundary_perc desc
limit 10; 
""")

            batter  runs  boundary_perc
0       AD Russell  2651          78.54
1         CH Gayle  4965          75.77
2  Abhishek Sharma  2241          73.54
3      YBK Jaiswal  2478          73.28
4     AC Gilchrist  2069          72.89
5         V Sehwag  2728          72.29
6         N Pooran  2375          70.65
7         DR Smith  2385          70.52
8        SR Watson  3874          68.25
9       GJ Maxwell  2819          68.04

In [251]:
q("""
--batter who scored the highest share of runs in boundary

select batter,
         sum(batter_runs) as runs,
         round(100.0 *sum(case when batter_runs in (4,6) 
         then batter_runs
         else 0
         end)/sum(batter_runs),2)as boundary_perc

from v_ball
group by batter
having runs>2000
order by boundary_perc desc
limit 10; 
""")

            batter  runs  boundary_perc
0       AD Russell  2651          78.54
1         CH Gayle  4965          75.77
2  Abhishek Sharma  2241          73.54
3      YBK Jaiswal  2478          73.28
4     AC Gilchrist  2069          72.89
5         V Sehwag  2728          72.29
6         N Pooran  2375          70.65
7         DR Smith  2385          70.52
8        SR Watson  3874          68.25
9       GJ Maxwell  2819          68.04

In [252]:
q("""
--find an ideal middle-order batter who can lift the run rate in over 7 to 15.

  select batter,sum(is_legal) as balls , sum (batter_runs) as runs,
            Round(100* sum(batter_runs)/sum(is_legal),2) as run_rate
from v_ball
where phase = 'Middle'
group by batter
order by run_rate desc
limit 20;
""")

             batter  balls  runs  run_rate
0        Auqib Nabi      1     4     400.0
1        Avesh Khan      4    12     300.0
2      Kamran Akmal     20    51     255.0
3        Akash Deep      2     5     250.0
4         KAJ Roach      2     5     250.0
5       Urvil Patel     11    26     236.0
6     V Suryavanshi     89   189     212.0
7     Priyansh Arya    110   225     204.0
8      Kartik Tyagi      2     4     200.0
9        C Connolly     90   178     197.0
10         A Mhatre     84   157     186.0
11   Vivrant Sharma     23    42     182.0
12          PD Salt    212   383     180.0
13          SD Hope     52    94     180.0
14  J Fraser-McGurk     49    87     177.0
15      PHKD Mendis     35    61     174.0
16        SP Narine    279   486     174.0
17     RD Rickelton    119   207     173.0
18         V Sehwag    611  1062     173.0
19  Abhishek Sharma    440   758     172.0

In [253]:
q("""
--find an ideal middle-order batter who can lift the run rate in over 7 to 15.

  select batter,sum(is_legal) as balls , sum (batter_runs) as runs,
            Round(100* sum(batter_runs)/sum(is_legal),2) as run_rate
from v_ball
where phase = 'Middle'
group by batter
having balls>500
order by run_rate desc
limit 20;
""")

             batter  balls  runs  run_rate
0          V Sehwag    611  1062     173.0
1        RM Patidar    566   970     171.0
2          N Pooran    848  1351     159.0
3         H Klaasen    697  1099     157.0
4          CH Gayle   1285  2011     156.0
5        AD Russell    767  1182     154.0
6         SR Watson   1302  2006     154.0
7        GJ Maxwell   1163  1780     153.0
8          SE Marsh    971  1448     149.0
9   B Sai Sudharsan    694  1031     148.0
10         DR Smith    675  1004     148.0
11       JC Buttler   1303  1890     145.0
12         SA Yadav   1845  2664     144.0
13     Shubman Gill   1300  1864     143.0
14       MA Agarwal    781  1094     140.0
15       RD Gaikwad    780  1093     140.0
16     Ishan Kishan   1091  1518     139.0
17          VR Iyer    524   731     139.0
18      YBK Jaiswal    582   811     139.0
19         KL Rahul   1740  2412     138.0

In [254]:
q("""
SELECT batter,
       SUM(is_legal) AS balls,
       SUM(batter_runs) AS runs,
       ROUND(100.0 * SUM(batter_runs) / SUM(is_legal), 2) AS strike_rate
FROM v_ball
where phase = 'Death'
GROUP BY batter
HAVING balls >= 50
ORDER BY strike_rate DESC
LIMIT 10;
""")

            batter  balls  runs  strike_rate
0          HM Amla     51   122       239.22
1       R Shepherd     73   168       230.14
2   AB de Villiers    829  1868       225.33
3   LS Livingstone    156   345       221.15
4  B Sai Sudharsan    118   246       208.47
5         CH Gayle    280   581       207.50
6         T Stubbs    257   533       207.39
7        Q de Kock    116   240       206.90
8       MA Agarwal    122   252       206.56
9          RR Pant    513  1035       201.75

In [255]:
q("""
SELECT batter,
       SUM(is_legal) AS balls,
       SUM(batter_runs) AS runs,
       ROUND(100.0 * SUM(batter_runs) / SUM(is_legal), 2) AS strike_rate
FROM v_ball
where phase = 'Powerplay'
GROUP BY batter
HAVING balls >= 50
ORDER BY strike_rate DESC
LIMIT 10;
""")

            batter  balls  runs  strike_rate
0    V Suryavanshi    202   467       231.19
1  J Fraser-McGurk    142   298       209.86
2    Priyansh Arya    301   603       200.33
3         A Mhatre    145   275       189.66
4          TM Head    493   884       179.31
5       P Nissanka    104   185       177.88
6          PD Salt    484   840       173.55
7  Abhishek Sharma    744  1287       172.98
8        SP Narine    688  1174       170.64
9       JG Bethell     55    93       169.09

In [256]:
q("""
-- who is the most reliable in a chase - strike  rate batting second ?

SELECT 
    batter,
    SUM(batter_runs) AS runs,
    SUM(is_legal) AS balls,
    ROUND(100.0 * SUM(batter_runs) / SUM(is_legal), 2) AS strike_rate

FROM v_ball
WHERE innings = 2
GROUP BY batter
HAVING balls > 500
ORDER BY strike_rate DESC
LIMIT 10;

""")

            batter  runs  balls  strike_rate
0        SP Narine   869    507       171.40
1       AD Russell  1130    660       171.21
2  Abhishek Sharma  1108    648       170.99
3         N Pooran  1218    729       167.08
4         V Sehwag  1427    869       164.21
5       GJ Maxwell  1164    734       158.58
6   P Simran Singh   832    527       157.87
7       JC Buttler  2289   1461       156.67
8      YBK Jaiswal  1351    875       154.40
9         SA Yadav  2131   1382       154.20

In [257]:
q("""
SELECT
    batter,
    SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) / NULLIF(SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END), 0),
        2
    ) AS strike_rate
FROM v_ball
WHERE phase = 'Death'
GROUP BY batter
HAVING balls >= 100
ORDER BY strike_rate DESC
LIMIT 10;
""")

            batter  balls  strike_rate
0   AB de Villiers    829       225.33
1   LS Livingstone    156       221.15
2  B Sai Sudharsan    118       208.47
3         CH Gayle    280       207.50
4         T Stubbs    257       207.39
5        Q de Kock    116       206.90
6       MA Agarwal    122       206.56
7          RR Pant    513       201.75
8         TH David    395       199.49
9       AD Russell    724       197.79

In [258]:
q("""SELECT batter,
        SUM(is_legal) AS balls,
        SUM(CASE WHEN 
            batter_runs=0 AND is_legal=1
            THEN 1 ELSE 0
            END) AS dot_balls,
        ROUND(100.0*SUM(CASE WHEN 
            batter_runs=0 AND is_legal=1
            THEN 1 ELSE 0
            END)/SUM(is_legal),2) AS
            dot_pct

FROM v_ball
WHERE phase='Death'
GROUP BY batter
HAVING balls >=500
ORDER BY dot_pct ASC
LIMIT 10;
""")

           batter  balls  dot_balls  dot_pct
0       JP Duminy    516        104    20.16
1  AB de Villiers    829        175    21.11
2        SK Raina    521        111    21.31
3        KL Rahul    502        110    21.91
4         V Kohli    807        185    22.92
5        DJ Bravo    516        128    24.81
6       AT Rayudu    692        173    25.00
7       DA Miller    835        212    25.39
8        AR Patel    629        162    25.76
9       RA Jadeja   1240        323    26.05

In [259]:
q("""
--how do runs and wickets differ across the three phases of an innings?

select phase,sum(is_legal)as balls,sum(total_runs),
round(6.0*sum(total_runs)/sum(is_legal),2)as runs_per_over,
round(100.0*sum(is_wicket)/sum(is_legal),2)as wicket_perc

from v_ball
group by phase;

""")

       phase   balls  sum(total_runs)  runs_per_over  wicket_perc
0      Death   62205           104056          10.04         8.46
1     Middle  128191           169160           7.92         4.34
2  Powerplay   86921           116397           8.03         4.01

In [260]:
q("""
--which over of the innings is the most expensive?


select over_number+1 as overs,
round (6.0*sum(total_runs)/sum(is_legal),2)as runs_per_over
from v_ball
group by over_number
order by runs_per_over desc;


""")

    overs  runs_per_over
0      20          11.39
1      19          10.53
2      18          10.12
3      17           9.46
4      16           9.05
5      15           8.74
6       6           8.68
7       5           8.65
8       4           8.63
9      14           8.43
10      3           8.37
11     13           8.17
12     12           8.13
13     11           7.96
14      9           7.77
15     10           7.66
16      2           7.60
17      8           7.47
18      7           6.98
19      1           6.28

In [261]:
q("""
--which over of the innings is the most expensive?


select over_number+1 as overs,
round (6.0*sum(total_runs)/sum(is_legal),2)as runs_per_over
from v_ball
group by over_number
order by runs_per_over desc;


""")

    overs  runs_per_over
0      20          11.39
1      19          10.53
2      18          10.12
3      17           9.46
4      16           9.05
5      15           8.74
6       6           8.68
7       5           8.65
8       4           8.63
9      14           8.43
10      3           8.37
11     13           8.17
12     12           8.13
13     11           7.96
14      9           7.77
15     10           7.66
16      2           7.60
17      8           7.47
18      7           6.98
19      1           6.28

In [262]:
q("""
SELECT ROUND(AVG(powerplay_runs), 2) AS avg_powerplay_score
FROM (
    SELECT
        match_id,
        innings,
        SUM(total_runs) AS powerplay_runs
    FROM v_ball
    WHERE phase = 'Powerplay' and innings in(1,2)
    GROUP BY match_id, innings);
""")

   avg_powerplay_score
0                48.14

In [263]:
q("""
SELECT bowler, SUM(bowler_wicket) AS total_wickets
FROM v_ball
GROUP BY bowler
ORDER BY total_wickets DESC;""")

               bowler  total_wickets
0           YS Chahal            228
1             B Kumar            215
2           SP Narine            199
3           PP Chawla            192
4            R Ashwin            187
..                ...            ...
563       Tilak Varma              0
564       VS Yeligati              0
565    Vivrant Sharma              0
566  Y Gnaneswara Rao              0
567       YBK Jaiswal              0

[568 rows x 2 columns]

In [264]:
q("""
SELECT
    over_number + 1 AS over,
    SUM(is_wicket) AS wickets
FROM v_ball
GROUP BY over_number
ORDER BY over_number DESC;
""")

    over  wickets
0     20     1433
1     19     1089
2     18     1055
3     17      863
4     16      824
5     15      764
6     14      703
7     13      661
8     12      621
9     11      635
10    10      554
11     9      593
12     8      534
13     7      497
14     6      585
15     5      640
16     4      597
17     3      606
18     2      567
19     1      488

In [265]:
q("""
SELECT bowler,SUM(bowler_wicket) AS wicket 
FROM v_ball
GROUP BY bowler
ORDER BY wicket DESC;
""")

               bowler  wicket
0           YS Chahal     228
1             B Kumar     215
2           SP Narine     199
3           PP Chawla     192
4            R Ashwin     187
..                ...     ...
563       Tilak Varma       0
564       VS Yeligati       0
565    Vivrant Sharma       0
566  Y Gnaneswara Rao       0
567       YBK Jaiswal       0

[568 rows x 2 columns]

In [266]:
q("""
SELECT 
    bowler,
    COUNT(*) AS legal_balls,
    SUM(total_runs) AS runs_conceded,
    ROUND(6.0 * SUM(total_runs) / COUNT(*), 2) AS economy
FROM v_ball
WHERE is_wide_ball = 0 
  AND is_no_ball = 0
GROUP BY bowler
HAVING COUNT(*) >= 500
ORDER BY economy ASC
LIMIT 10;
""")

            bowler  legal_balls  runs_conceded  economy
0         A Kumble          965           1050     6.53
1   M Muralitharan         1524           1690     6.65
2         DW Steyn         2176           2438     6.72
3        SP Narine         4507           5103     6.79
4       DL Vettori          777            886     6.84
5          J Botha          694            799     6.91
6       SL Malinga         2827           3291     6.98
7  Harbhajan Singh         3416           3996     7.02
8         R Ashwin         4710           5521     7.03
9         R Sharma          928           1093     7.07

In [267]:
q(""" 
  --which bowler takes a wicket most oftrn - best strike rate in balls per wicket
  --bowler,total ball,total wicket,ball per wicket

SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(bowler_wicket) AS total_wickets,
    ROUND(
        1.0 * SUM(is_legal) / SUM(bowler_wicket),
        2
    ) AS balls_per_wicket
FROM v_ball
GROUP BY bowler
HAVING total_wickets > 50
ORDER BY balls_per_wicket asc
LIMIT 10;
""")

         bowler  total_balls  total_wickets  balls_per_wicket
0    AD Russell         1806            123             14.68
1  JR Hazlewood         1008             65             15.51
2      K Rabada         2112            133             15.88
3      MA Starc         1083             68             15.93
4   Imran Tahir         1316             82             16.05
5      HV Patel         2470            151             16.36
6    SL Malinga         2827            170             16.63
7      DJ Bravo         3120            183             17.05
8     YS Chahal         3941            228             17.29
9    Noor Ahmad          966             55             17.56

In [268]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END) AS boundaries,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS boundary_perc
FROM v_ball
GROUP BY bowler
HAVING SUM(is_legal) >= 1000
ORDER BY boundary_perc ASC
LIMIT 10;
""")

            bowler  balls  boundaries  boundary_perc
0   M Muralitharan   1524         170          11.15
1         R Bhatia   1636         188          11.49
2        SP Narine   4507         526          11.67
3         R Ashwin   4710         555          11.78
4         M Kartik   1149         138          12.01
5         SK Warne   1194         147          12.31
6         A Mishra   3371         423          12.55
7          PP Ojha   1899         243          12.80
8      Rashid Khan   3387         436          12.87
9  Harbhajan Singh   3416         441          12.91

In [269]:
q("""
SELECT
    bowler,
    SUM(CASE WHEN is_legal = 1 AND batter_runs = 0 THEN 1 ELSE 0 END) AS dot_balls
FROM v_ball
GROUP BY bowler
ORDER BY dot_balls DESC
LIMIT 10;
""")

            bowler  dot_balls
0          B Kumar       1935
1        SP Narine       1788
2         R Ashwin       1663
3        JJ Bumrah       1485
4        RA Jadeja       1379
5        PP Chawla       1358
6        YS Chahal       1353
7  Harbhajan Singh       1312
8      Rashid Khan       1270
9         UT Yadav       1260

In [270]:
q("""
-- Which bowler bowls the most dot balls?
-- bowler ,balls,dot_ball,dot_perc?


SELECT bowler,SUM(is_legal)AS balls,sum(CASE WHEN total_runs = 0 AND is_legal=1
                            THEN 1
                            ELSE 0
                            END) AS dot_balls,
                    ROUND(100.0*sum(CASE WHEN total_runs = 0 AND is_legal=1
                            THEN 1
                            ELSE 0
                            END)/SUM(is_legal),2)AS dot_perc
FROM v_ball
GROUP BY bowler
HAVING balls >= 1000
ORDER BY dot_perc DESC
LIMIT 10;
""")

         bowler  balls  dot_balls  dot_perc
0      DW Steyn   2176       1019     46.83
1     JC Archer   1440        627     43.54
2      MM Patel   1355        590     43.54
3      M Morkel   1629        708     43.46
4    MG Johnson   1232        533     43.26
5  JR Hazlewood   1008        434     43.06
6       P Kumar   2524       1075     42.59
7     DL Chahar   1954        827     42.32
8      RP Singh   1775        744     41.92
9       A Nehra   1908        798     41.82

In [271]:
q("""SELECT wicket_kind,COUNT(*) AS n
FROM v_ball
WHERE is_wicket=1
GROUP BY wicket_kind
ORDER BY n DESC;
""")

             wicket_kind     n
0                 caught  9045
1                 bowled  2398
2                run out  1167
3                    lbw   871
4      caught and bowled   399
5                stumped   382
6           retired hurt    19
7             hit wicket    18
8            retired out     6
9  obstructing the field     4

In [272]:
q("""SELECT CASE WHEN bowler_type LIKE                     
       '%Legbreak%' OR bowler_type LIKE 
       '%Offbreak%' OR bowler_type LIKE 
       '%Orthodox%' OR bowler_type LIKE 
       '%Wrist spin%' OR bowler_type LIKE 
       '%Googly%' THEN 'Spin' ELSE 'Pace' 
       END AS style,                                  
       SUM(is_legal) AS balls,                           
       ROUND(6.0*SUM(bowler_runs)/SUM(is_legal),2)      
              AS economy, 
       ROUND(100.0*SUM(bowler_wicket)/SUM(is_legal),2)   
              AS wicket_pct 
FROM   v_ball                                           
WHERE  bowler_type IS NOT NULL AND                        
       TRIM(bowler_type) <> '' 
GROUP  BY style;    
""")

  style   balls  economy  wicket_pct
0  Pace  176859     8.57        4.93
1  Spin  100129     7.76        4.37

In [273]:
q("""
SELECT
    CASE
        WHEN bowler_type LIKE 'Left%'
        THEN 'Left arm'
        ELSE 'Right arm'
    END AS arm,

    batsman_type,

    ROUND(
        6.0 * SUM(bowler_runs) / SUM(is_legal),
        2
    ) AS economy,

    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_pct

FROM v_ball

WHERE TRIM(COALESCE(bowler_type, '')) <> ''
  AND batsman_type IS NOT NULL

GROUP BY arm, batsman_type;
""")

         arm    batsman_type  economy  wicket_pct
0   Left arm   Left hand Bat     8.81        5.13
1   Left arm  Right hand Bat     8.49        4.97
2  Right arm   Left hand Bat     8.33        4.46
3  Right arm  Right hand Bat     8.16        4.78

In [274]:
q("""
SELECT
    bowler,
    SUM(bowler_wicket) AS wicket,
    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_perc
FROM v_ball
WHERE bowler_type LIKE '%Legbreak%'
   OR bowler_type LIKE '%Offbreak%'
   OR bowler_type LIKE '%Orthodox%'
   OR bowler_type LIKE '%Wrist spin%'
   OR bowler_type LIKE '%Googly%'
GROUP BY bowler
HAVING SUM(is_legal) >= 1000
ORDER BY wicket DESC
LIMIT 10;
""")

            bowler  wicket  wicket_perc
0        YS Chahal     228         5.79
1        SP Narine     199         4.42
2        PP Chawla     192         4.99
3         R Ashwin     187         3.97
4        RA Jadeja     177         4.23
5         A Mishra     174         5.16
6      Rashid Khan     168         4.96
7  Harbhajan Singh     150         4.39
8         AR Patel     136         3.90
9    Kuldeep Yadav     109         4.90

In [275]:
q("""

--we need a death-over bowler.who is cheapest in over 16 to 20?
--bowler,balls,bowler_runs,economy

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_runs) AS bowler_runs,
    ROUND(6.0 * SUM(bowler_runs) / SUM(is_legal), 2) AS economy
FROM v_ball
WHERE over_number BETWEEN 15 AND 19
GROUP BY bowler
HAVING SUM(is_legal) >=300
ORDER BY economy ASC
LIMIT 10;

""")

        bowler  balls  bowler_runs  economy
0    SP Narine   1075         1307     7.29
1   SL Malinga   1117         1464     7.86
2    JJ Bumrah   1393         1911     8.23
3     R Ashwin    601          825     8.24
4     DW Steyn    634          877     8.30
5     CV Varun    310          432     8.36
6  Rashid Khan    594          829     8.37
7     AR Patel    376          539     8.60
8    PP Chawla    444          641     8.66
9    CH Morris    646          933     8.67

In [276]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_wicket) AS wickets,
    ROUND(100.0 * SUM(bowler_wicket) / SUM(is_legal), 2) AS wicket_perc
    FROM v_ball
    WHERE over_number BETWEEN 0 AND 5
    GROUP BY bowler
    HAVING balls > 300
    ORDER BY wickets DESC
    LIMIT 10;
    """)

           bowler  balls  wickets  wicket_perc
0         B Kumar   2453       89         3.63
1        TA Boult   1644       72         4.38
2       DL Chahar   1527       67         4.39
3  Sandeep Sharma   1728       64         3.70
4        UT Yadav   1446       58         4.01
5        I Sharma   1521       57         3.75
6  Mohammed Shami   1584       57         3.60
7          Z Khan   1292       52         4.02
8  Mohammed Siraj   1326       50         3.77
9        R Ashwin   1252       50         3.99

In [277]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(is_legal AND total_runs = 0) AS dot_balls,
    ROUND(100.0 * SUM(is_legal AND total_runs = 0) / SUM(is_legal), 2) AS dot_perc
FROM v_ball
WHERE phase = 'Death'
GROUP BY bowler
HAVING balls >= 300
ORDER BY dot_perc DESC
LIMIT 10;
""")

              bowler  balls  dot_balls  dot_perc
0          SP Narine   1075        397     36.93
1           CV Varun    310        112     36.13
2         MG Johnson    302        108     35.76
3        Rashid Khan    594        208     35.02
4           DW Steyn    634        218     34.38
5          PP Chawla    444        150     33.78
6           K Rabada    660        222     33.64
7  M Prasidh Krishna    542        182     33.58
8           A Mishra    521        167     32.05
9           MA Starc    333        106     31.83

In [278]:
run_sql_file(r'C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\08_matches_clean.sql')

ran C:\Users\muham\OneDrive\Desktop\PROJECT_5.1\2\project 3.1 sem3\sql\08_matches_clean.sql

In [279]:
q("""
SELECT
    COUNT(*) AS decisive_matches,

    SUM(
        CASE
            WHEN toss_winner = match_winner THEN 1
            ELSE 0
        END
    ) AS toss_winner_won,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN toss_winner = match_winner THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS pct

FROM matches_clean
WHERE result = 'win';
""")

   decisive_matches  toss_winner_won    pct
0              1187              613  51.64

In [280]:
q("""
SELECT
    LOWER(toss_decision) AS decision,
    COUNT(*) AS total_tosses,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM matches_clean), 2) AS pct
FROM matches_clean
GROUP BY LOWER(toss_decision);
""")

  decision  total_tosses    pct
0      bat           412  33.99
1    field           800  66.01

In [281]:
q("""select count(*)from matches_clean;""")

   count(*)
0      1212

In [282]:
q("""
SELECT
    toss_winner,
    COUNT(*) AS toss_won
FROM matches_clean
GROUP BY toss_winner
ORDER BY toss_won DESC;
""")

                    toss_winner  toss_won
0                Mumbai Indians       156
1                Delhi Capitals       145
2           Sunrisers Hyderabad       139
3              Rajasthan Royals       134
4   Royal Challengers Bangalore       132
5         Kolkata Knight Riders       132
6           Chennai Super Kings       130
7                  Punjab Kings       126
8                Gujarat Titans        33
9          Lucknow Super Giants        29
10                Pune Warriors        20
11                Gujarat Lions        15
12       Rising Pune Supergiant        13
13         Kochi Tuskers Kerala         8

In [283]:
q("""select * from v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,225,Rajasthan Royals,1

In [284]:
q("""
SELECT ROUND(AVG(first_innings_runs), 2) AS average_first_innings_score
FROM v_match_totals;
""")

   average_first_innings_score
0                       168.19

In [285]:
q("""
SELECT
    innings,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE innings IN (1, 2)
GROUP BY innings
ORDER BY innings;
""")

   innings  run_rate
0        1      8.49
1        2      8.37

In [286]:
q("""
SELECT
    CASE innings
        WHEN 1 THEN 'Batting first'
        WHEN 2 THEN 'Batting second'
    END AS batting_order,
    ROUND(AVG(wickets), 2) AS average_wickets_lost
FROM v_innings
GROUP BY innings
ORDER BY average_wickets_lost DESC;
""")

    batting_order  average_wickets_lost
0   Batting first                  6.13
1  Batting second                  5.70

In [287]:
q("""
SELECT
    COUNT(*) AS match_with_200plus,
    SUM(chase_won) AS successfully_chased 

    FROM v_match_totals
    WHERE first_innings_runs >=200;
    
""")

   match_with_200plus  successfully_chased
0                 198                   46

In [288]:
q("""
SELECT
    MAX(CASE WHEN chase_won = 0 THEN first_innings_runs END) AS biggest_defend,
    MAX(CASE WHEN chase_won = 1 THEN first_innings_runs END) AS biggest_chased
FROM v_match_totals;
""")

   biggest_defend  biggest_chased
0             287             264

In [289]:
q("""
SELECT
    venue_clean AS ground,
    COUNT(*) AS matches_hosted
FROM matches_clean
WHERE venue_clean IS NOT NULL
  AND TRIM(venue_clean) <> ''
GROUP BY venue_clean
ORDER BY matches_hosted DESC
LIMIT 10;
""")

                                ground  matches_hosted
0                     Wankhede Stadium             130
1                M Chinnaswamy Stadium             104
2                         Eden Gardens             104
3               MA Chidambaram Stadium              95
4   Rajiv Gandhi International Stadium              87
5               Sawai Mansingh Stadium              66
6                     Feroz Shah Kotla              60
7  Dubai International Cricket Stadium              46
8                 Arun Jaitley Stadium              41
9                Narendra Modi Stadium              37

In [290]:
q("""SELECT m.venue_clean,
       COUNT(DISTINCT m.match_id) AS matches,
       ROUND(AVG(i.runs), 2) AS avg_score
FROM matches_clean m
JOIN v_innings i ON i.match_id = m.match_id
GROUP BY m.venue_clean
HAVING matches >= 25
ORDER BY avg_score DESC
LIMIT 10;
""")

                                         venue_clean  matches  avg_score
0                               Arun Jaitley Stadium       41     180.04
1                              Narendra Modi Stadium       37     177.82
2                                  Brabourne Stadium       27     172.31
3       Punjab Cricket Association IS Bindra Stadium       26     170.71
4  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26     167.59
5                                   Wankhede Stadium      130     166.95
6                              M Chinnaswamy Stadium      104     165.67
7                             Sawai Mansingh Stadium       66     161.11
8                 Rajiv Gandhi International Stadium       87     161.06
9                                       Eden Gardens      104     160.94

In [291]:
q("""
SELECT
    match_winner AS team,
    COUNT(*) AS wins
FROM matches_clean
WHERE RESULT='win'
GROUP BY match_winner
ORDER BY wins DESC
LIMIT 10;
""")

                          team  wins
0               Mumbai Indians   153
1          Chennai Super Kings   145
2  Royal Challengers Bangalore   138
3        Kolkata Knight Riders   136
4          Sunrisers Hyderabad   128
5                 Punjab Kings   125
6               Delhi Capitals   122
7             Rajasthan Royals   120
8               Gujarat Titans    42
9         Lucknow Super Giants    32

In [292]:
q("""
SELECT
    batting_team AS team,
    SUM(total_runs) AS powerplay_runs,
    SUM(is_legal) AS legal_balls,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE phase = 'Powerplay'
GROUP BY batting_team
HAVING legal_balls > 3000
ORDER BY run_rate DESC;
""")

                          team  powerplay_runs  legal_balls  run_rate
0                 Punjab Kings           13344         9755      8.21
1          Sunrisers Hyderabad           13712        10034      8.20
2             Rajasthan Royals           11797         8768      8.07
3               Delhi Capitals           13237         9893      8.03
4        Kolkata Knight Riders           13016         9738      8.02
5               Mumbai Indians           13561        10257      7.93
6  Royal Challengers Bangalore           13196        10008      7.91
7          Chennai Super Kings           12198         9324      7.85

In [293]:
q("""
SELECT
    batting_team,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN batter_runs IN (4, 6) THEN batter_runs
                ELSE 0
            END
        ) / NULLIF(SUM(batter_runs), 0),
        2
    ) AS boundary_run_percentage
FROM v_ball
GROUP BY batting_team
HAVING SUM(is_legal) >= 10000
ORDER BY boundary_run_percentage DESC;
""")

                  batting_team  boundary_run_percentage
0               Mumbai Indians                    62.30
1        Kolkata Knight Riders                    61.84
2                 Punjab Kings                    61.67
3  Royal Challengers Bangalore                    61.44
4             Rajasthan Royals                    60.90
5               Delhi Capitals                    59.97
6          Chennai Super Kings                    59.80
7          Sunrisers Hyderabad                    58.50

In [294]:
q("""
SELECT
    player_of_match AS player,
    COUNT(*) AS awards
FROM matches_clean
WHERE player_of_match IS NOT NULL
  AND TRIM(player_of_match) <> ''
GROUP BY player_of_match
ORDER BY awards DESC
LIMIT 10;
""")

           player  awards
0  AB de Villiers      25
1        CH Gayle      22
2       RG Sharma      21
3         V Kohli      20
4        MS Dhoni      18
5       DA Warner      18
6       SP Narine      17
7       RA Jadeja      17
8        KL Rahul      17
9       YK Pathan      16

In [295]:
q("""
WITH wicket_counts AS (
    SELECT
        phase,
        wicket_kind,
        COUNT(*) AS dismissals
    FROM v_ball
    WHERE is_wicket = 1
      AND wicket_kind IS NOT NULL
    GROUP BY phase, wicket_kind
)
SELECT
    phase,
    wicket_kind,
    dismissals,
    ROUND(
        100.0 * dismissals
        / SUM(dismissals) OVER (PARTITION BY phase),
        2
    ) AS dismissal_percentage
FROM wicket_counts
ORDER BY
    CASE phase
        WHEN 'Powerplay' THEN 1
        WHEN 'Middle' THEN 2
        WHEN 'Death' THEN 3
        ELSE 4
    END,
    dismissals DESC;
""")

        phase            wicket_kind  dismissals  dismissal_percentage
0   Powerplay                 caught        2272                 65.23
1   Powerplay                 bowled         612                 17.57
2   Powerplay                    lbw         270                  7.75
3   Powerplay                run out         189                  5.43
4   Powerplay      caught and bowled          79                  2.27
5   Powerplay                stumped          49                  1.41
6   Powerplay           retired hurt           8                  0.23
7   Powerplay             hit wicket           3                  0.09
8   Powerplay  obstructing the field           1                  0.03
9      Middle                 caught        3484                 62.64
10     Middle                 bowled         909                 16.34
11     Middle                    lbw         384                  6.90
12     Middle                run out         344                  6.18
13     Middle                stumped         242                  4.35
14     Middle      caught and bowled         189                  3.40
15     Middle           retired hurt           5                  0.09
16     Middle             hit wicket           4                  0.07
17     Middle            retired out           1                  0.02
18      Death                 caught        3289                 62.48
19      Death                 bowled         877                 16.66
20      Death                run out         634                 12.04
21      Death                    lbw         217                  4.12
22      Death      caught and bowled         131                  2.49
23      Death                stumped          91                  1.73
24      Death             hit wicket          11                  0.21
25      Death           retired hurt           6                  0.11
26      Death            retired out           5                  0.09
27      Death  obstructing the field           3                  0.06

In [299]:
q("""
SELECT
    player_out AS batter,
    COUNT(*) AS run_outs
FROM v_ball
WHERE LOWER(wicket_kind) = 'run out'
  AND player_out IS NOT NULL
GROUP BY player_out
ORDER BY run_outs DESC
LIMIT 10;
""")

            batter  run_outs
0         S Dhawan        16
1        G Gambhir        16
2         SK Raina        15
3       KD Karthik        15
4        AT Rayudu        15
5   AB de Villiers        14
6          M Vijay        12
7     F du Plessis        12
8        YK Pathan        11
9  Y Venugopal Rao        11

In [301]:
q("""
SELECT
    season_year,
    COUNT(DISTINCT match_id) AS matches_played
FROM matches_clean
GROUP BY season_year
ORDER BY season_year;
""")

    season_year  matches_played
0          2008              58
1          2009              57
2          2010              60
3          2011              73
4          2012              74
5          2013              76
6          2014              60
7          2015              59
8          2016              60
9          2017              59
10         2018              60
11         2019              60
12         2020              60
13         2021              60
14         2022              74
15         2023              74
16         2024              71
17         2025              74
18         2026              43

In [303]:
q("""
SELECT
    player_out AS batter,
    bowler,
    COUNT(*) AS dismissals
FROM v_ball
WHERE is_wicket = 1
  AND player_out IS NOT NULL
  AND LOWER(wicket_kind) <> 'run out'
GROUP BY player_out, bowler
ORDER BY dismissals DESC
LIMIT 10;
""")

       batter          bowler  dismissals
0   RG Sharma       SP Narine           8
1   AM Rahane         B Kumar           7
2   AT Rayudu       MM Sharma           7
3  MA Agarwal       YS Chahal           7
4    MS Dhoni          Z Khan           7
5   RG Sharma        A Mishra           7
6     RR Pant       JJ Bumrah           7
7  RV Uthappa        R Ashwin           7
8     V Kohli  Sandeep Sharma           7
9   AM Rahane        R Ashwin           6

In [307]:
q("""
SELECT 
    batter,
    SUM(is_legal) AS balls,
    SUM(batter_runs) AS runs,
    ROUND(
        100.0 * SUM(batter_runs) / SUM(is_legal),
        2
    ) AS sr
FROM v_ball
WHERE phase = 'Powerplay' 
  AND is_wicket = 0
GROUP BY batter
HAVING balls >= 500
ORDER BY sr DESC
limit 10;
""")

            batter  balls  runs      sr
0        SP Narine    640  1174  183.44
1  Abhishek Sharma    712  1287  180.76
2      YBK Jaiswal    948  1579  166.56
3   P Simran Singh    658  1070  162.61
4      JM Bairstow    601   944  157.07
5          PP Shaw    866  1347  155.54
6         V Sehwag   1036  1593  153.76
7          CA Lynn    520   779  149.81
8      RA Tripathi    685  1013  147.88
9       JC Buttler   1216  1788  147.04

In [ ]:
pd.read_sql("""
SELECT type, name
FROM sqlite_master
WHERE type IN ('table', 'view')
ORDER BY type, name;
""", con)